name: KiCAD ERC & DRC
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add KiCAD APT reposity
        run: |
          sudo add-apt-repository ppa:kicad/kicad-dev-nightly
          sudo apt update
          
      - name: Install KiCAD (nightly build)
        run: sudo apt install kicad-nightly

      - name: Get KiCad version
        run: kicad-cli-nightly version

      - name: Get KiCad version
        run: ls -R $GITHUB_WORKSPACE

      - name: Run ERC on SCH(ematics)
        run: /usr/bin/kicad-cli-nightly sch erc $GITHUB_WORKSPACE/mini_cicd_tests/mini_cicd_tests.kicad_sch

      - name: Run DRC on PCB (Board)
        run: /usr/bin/kicad-cli-nightly pcb drc $GITHUB_WORKSPACE/mini_cicd_tests/mini_cicd_tests.kicad_pcb

      - name: Export PDF from SCH
        run: /usr/bin/kicad-cli-nightly sch export pdf $GITHUB_WORKSPACE/mini_cicd_tests/mini_cicd_tests.kicad_sch
        
      - name: Export PDF from PCB
        run: /usr/bin/kicad-cli-nightly pcb export pdf $GITHUB_WORKSPACE/mini_cicd_tests/mini_cicd_tests.kicad_pcb
