name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Add KiCAD APT reposity
        run: |
          sudo add-apt-repository ppa:kicad/kicad-dev-nightly
          sudo apt update
          
      - name: Install KiCAD (nightly build)
        run: sudo apt install kicad-nightly
        
      - name: Get KiCad version
        run: kicad-cli version

