name: KiCAD ERC & DRC
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Add KiCAD APT reposity
        run: |
          sudo add-apt-repository ppa:kicad/kicad-dev-nightly
          sudo apt update
          
      - name: Install KiCAD (nightly build)
        run: sudo apt install kicad-nightly

      - name: Get KiCad version
        run: kicad-cli-nightly version

      - name: Check Schematics with ERC
        run: /usr/bin/kicad-cli-nightly sch erc mini_cicd_tests/mini_cicd_tests.kicad_sch

      - name: Check PCB with DRC
        run: /usr/bin/kicad-cli-nightly pcb drc mini_cicd_tests/mini_cicd_tests.kicad_pcb

      - name: Export PDF from schematics
        run: /usr/bin/kicad-cli-nightly sch export pdf mini_cicd_tests/mini_cicd_tests.kicad_sch
        
      - name: Export PDF from schematics
        run: /usr/bin/kicad-cli-nightly pcb export pdf mini_cicd_tests/mini_cicd_tests.kicad_pcb

      - name: Export PDF from schematics
        run: /usr/bin/kicad-cli-nightly sch export pdf mini_cicd_tests/mini_cicd_tests.kicad_sch
