name: KiCAD ERC & DRC
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Add KiCAD APT reposity
        run: |
          sudo add-apt-repository ppa:kicad/kicad-dev-nightly
          sudo apt update
          
      - name: Install KiCAD (nightly build)
        run: sudo apt install kicad-nightly
        
      - name: Get KiCad version
        run: |
          ls -ltR /usr
          ls -ltR /var

      - name: Get KiCad version
        run: kicad-cli-nightly version

      - name: Get KiCad version
        run: /usr/bin/kicad-cli-nightly version
        # /usr/bin/kicad-cli-nightly

      - name: Check Schematics with ERC
        run: /usr/bin/kicad-cli-nightly version
        # /usr/bin/kicad-cli-nightly

      - name: Check PCB with DRC
        run: /usr/bin/kicad-cli-nightly version
        # /usr/bin/kicad-cli-nightly

      - name: Export PDF from schematics
        run: /usr/bin/kicad-cli-nightly sch export pdf xxx.sch

